runtime: custom
env: flex

service: your-service-name  # Replace with your desired service name

# Specify the Docker image to use (replace details)
image: europe-west1-qwiklabs-gcp-01-ec162502d964.pkg.dev/repositories/emily-backend:tag

# Configure health checks (optional)
livenessProbe:
  httpGet:
    path: /healthz  # Replace with your health check path (if applicable)
    port: 80

readinessProbe:
  httpGet:
    path: /healthz  # Replace with your health check path (if applicable)
    port: 80